Traceback (most recent call last):
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/gsw/anaconda3/envs/f540jbook/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#-----------------------------
#Pacote para manipular vetores e matrizes
import numpy as np
import pandas as pd
#-----------------------------
#Pacotes para lidar com unidades
from astropy import units as un
from astropy import constants as cte
#-----------------------------
#pacote para gr√°ficos
import matplotlib.pyplot as plt
import matplotlib
#Comandos opcionais para formatar gr√°fico
font = {'family' : 'Arial',
        'weight' : 'normal',
        'size'   : 12}	
lines = {'linewidth' : 3.0}
figure = {'figsize' : [6.0, 6/1.6]}
matplotlib.rc('font', **font)
matplotlib.rc('lines', **lines)
matplotlib.rc('figure', **figure)
#-----------------------------
from myst_nb import glue
#pacote para desenhar circuitos
import SchemDraw as schem
import SchemDraw.elements as e
d = schem.Drawing(unit=2.5) # unit=2.5 determina o tamanho dos componentes
# %config InlineBackend.figure_format = 'svg'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-a072a29bceed>[0m in [0;36m<module>[0;34m[0m
[1;32m     23[0m [0;32mfrom[0m [0mmyst_nb[0m [0;32mimport[0m [0mglue[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m [0;31m#pacote para desenhar circuitos[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 25[0;31m [0;32mimport[0m [0mSchemDraw[0m [0;32mas[0m [0mschem[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m [0;32mimport[0m [0mSchemDraw[0m[0;34m.[0m[0melements[0m [0;32mas[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m [0md[0m [0;34m=[0m [0mschem[0m[0;34m.[0m[0mDrawing[0m[0;34m([0m[0munit[0m[0;34m=[0m[0;36m2.5[0m[0;34m)[0m [0;31m# unit=2.5 determina o tamanho dos componentes[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'SchemDraw'
ModuleNotFoundError: No module named 'SchemDraw'

